### ISSUE TITLE
Issue Launching Application

### ISSUE THREAD

**Issue by JerJohn15** [octaviospain/Musicott#5]
Hello @octaviospain,

I want to launch this application so I can test it and, perhaps, add some  unit tests to it. However, after I followed the instructions you outlined in your README file, and entered  the, ```java -cp target/Musicott-x.y.z.jar com.transgressoft.musicott.MusicottApplication``` command I got this message:  

```Error: Could not find or load main class com.transgressoft.musicott.MusicottApplication```. 

I'm assuming that the  supposed "x.y.z" jar file is referring to the "musicott-0.9.1-b.jar" file included in the target folder, so I tried to enter "0.9.1-b" where the "x.y.z" is in the above command but still got the same error message.

**Comment by JerJohn15** [comment]
I'm attempting to install this application on a Window's 7 virtual machine however, I am unable to do so because it is saying that my operating system version is not supposed. I was running a 32bit version of Windows 7. Will this currently only work with 64 bit versions of Window's?

**Comment by octaviospain** [comment]
Hello @JerJohn15. You should be able to run this application on a Windows 32 bit version, it depends of the installed Java version, check if you installed the 32 or 64 bits version.

I updated the README file, instead of running that command, try running:
```
mvn package
mvn exec:java -D exec.mainClass=com.transgressoft.musicott.MusicottApplication
```

**Comment by JerJohn15** [comment]
@octaviospain,

Thanks for responding back. I was able to launch the program now. I might attempt to get it working on Window's at some point in the near future (it was really just a last resort if I couldn't get it to work on Linux). 

You mentioned for making tests to use the "tests" branch, what tool are you using for creating unit tests, junit?

**Comment by octaviospain** [comment]
Good to know that its working now :)

Yes, create the tests in the correct packages in the `tests` branch, and once covered the maximum lines possible, finally make the pull request.
I'm using JUnit 3 for tests that needs some mocking, JUnit 4 for more _standard_ tests, and [TestFX](https://github.com/TestFX/TestFX) for application tests and classes that needs the JavaFX toolkit.

For this last situation, I extend from [JavaFxTestBase](https://github.com/octaviospain/Musicott/blob/tests/test/com/transgressoft/musicott/tests/JavaFxTestBase.java) class. Check how I made it work in [NativePlayerTest](https://github.com/octaviospain/Musicott/blob/tests/test/com/transgressoft/musicott/player/NativePlayerTest.java).

As a suggestion you could start making tests for `MetadataUpdater`class (I already write an [initial skeleton test class](https://github.com/octaviospain/Musicott/blob/tests/test/com/transgressoft/musicott/util/MetadataUpdaterTest.java)), [SaveMusicLibrary](https://github.com/octaviospain/Musicott/blob/master/src/com/transgressoft/musicott/tasks/SaveMusicLibraryTask.java) class, or [Playlist](https://github.com/octaviospain/Musicott/blob/master/src/com/transgressoft/musicott/model/Playlist.java) class.

I have to say that TravisCI and CodeCov aren't prepared to properly run JUnit 4 and TestFX tests, so if you see that the build fails its because of that.

Thanks for contributing ;) !

**Comment by JerJohn15** [comment]
@octaviospain, 

Sure thing. I'll play around with the application a bit to get a feel for it and create some unit tests as you suggested. 

BTW, you can go ahead and close this issue now as my initial problem has been solved. If there are any additional questions or concerns I'll make a new thread.

**Comment by octaviospain** [comment]
Good to know. I will follow up
