### ISSUE TITLE
Playlists Drag&Drop feature request. Importing big folders make the progress bar stop working

### ISSUE THREAD

**Issue by goxr3plus** [octaviospain/Musicott#7]
Hello Octavio , i couldn't find an email so i can contact you , i like your project very much and i am studying it's code.
I am also developing and advanced media player in JavaFX 2 years now , you can check it here -> https://github.com/goxr3plus/XR3Player
I think that we can build something very good together , by sharing ideas and code :) , though both our applications are for the same reason and opensource.

---
 As a modern application Musicott should have drag and drop features , i mean on the playlists the user should be able to drop one or more folders or songs and the application to import them automatically.

The procedure of going on Menu->Import Folder or Files is very annoying.... really . I tried all the features today , except from the LastFM which i think is awesome :).

On the below image you can see all of 3 problems at once :

![untitled](https://user-images.githubusercontent.com/20374208/27015615-dc5d96be-4f1a-11e7-88cd-b9b4a4166191.png)

Also found another issues like 
1) **waveform is not drawn for many songs** 
2) **skip doesn't work for big files 150 megabytes etc** 

Some more user interface problems also , **like when you click the plus button the Menu appears on the other side of the screen :**

![untitled2](https://user-images.githubusercontent.com/20374208/27015629-7a56739a-4f1b-11e7-9b8d-66b2355858f4.png)

I wish someone came to me and said reported all these errors , cause actually it provides a way to improve the application by errors you may have never spotted :).

**Comment by octaviospain** [comment]
Hello @goxr3plus, I'm happy that you like the project and discovered errors, I really was waiting for someone to do it!

First of all, there are __many__ features that I want to implement in Musicott, but I don't have enough time, since I'm still studying and since now on also working. If you think you can add a feature you are free to do it and create a pull request! I will be happy to see that.

About the issues you mention:
* If some labels doesn't show any information is because the audio files doesn't contain that metadata. There is no error there. Maybe the music application you have been used only stores the information about songs in a intern database or something but doesn't update the file metadata. Musicott does every time you edit a track.
* About the context menu in the NavigationPane, try to change this code please. Inside the `initialize` method of the [`NavigationController`](https://github.com/octaviospain/Musicott/blob/master/application/src/com/transgressoft/musicott/view/NavigationController.java#L95) class, change lines 95-96:
```
double newPlaylistButtonX = e.getScreenX() + 10.0;
double newPlaylistButtonY = e.getScreenY() + 10.0;
```
for
```
double newPlaylistButtonX = newPlaylistButton.getLayoutX() + 150;
double newPlaylistButtonY = newPlaylistButton.getLayoutY();
```

The fix is tweaking around there, try ; )

* About the import progress bar freezed and the skipping big files, please try to debug the process when importing files. Specifically, the class you can debug around is [`AudioFilesParseAction`](https://github.com/octaviospain/Musicott/blob/master/application/src/com/transgressoft/musicott/tasks/parse/audiofiles/AudioFilesParseAction.java)
* Some waveforms are not displayed because some files are not supported. FLAC files or m4a files with Apple encoding (ALAC) can't be played, but they can be imported to the music library and edit its metadata. If you played some track and the waveform wasn't displayed, I'm sorry to tell you that the way waveforms are calculated is rudimentary, an inefficient for __non wav__ files. It transcodes the files into a wav file just to extract the waveform, check the code in [`WaveformTask`](https://github.com/octaviospain/Musicott/blob/master/application/src/com/transgressoft/musicott/tasks/WaveformTask.java). However, it works for most of the files, at least in my computer.

About possible project collaboration, it would be great of course. Write me to octaviospain[at]gmail.com, you could have found it looking in the commit registry.
